### ISSUE TITLE
[Fragment] Order is not respected when using fragment

### ISSUE THREAD

**Issue by youzi** [vigour-io/brisky-core#10]

**Comment by jimdebeer** [comment]
this will be fixed by using an array vs a real document fragment

**Comment by jimdebeer** [comment]
order
use something like frag order in order indexing

hard cases --

- static items in a frag (need to be ordered as non static items)
- 10 double check the cParent check in order -- seems wrong since the __c can change and from that point your screwed in order -- we need to store this on the subs thing and take the refs to parent out of there WRONG!

**Comment by jimdebeer** [comment]
-- try to restructure order not referencing parent at all -- store the orders / keys and indexes when making the map /w ids -- so we add INDEX in the subs map and pass it along as an argument -- this is by far the best strategy
